/**
 * Champ `keywords` des metadata (signal faible chez Google mais utile comme
 * référence sémantique / certains outils). JSON-LD réutilise une partie via
 * knowsAbout.
 */
export const SITE_KEYWORDS: readonly string[] = [
  "Vallerio Studio",
  "vallerio studio",
  "studio digital Annecy",
  "studio création site Annecy",
  "studio web Annecy",
  "petite agence web Annecy",
  "agence web Annecy",
  "agence digitale Annecy",
  "agence de communication Annecy",
  "agence création site Annecy",
  "agence site internet Annecy",
  "cabinet web Annecy",
  "freelance web Annecy",
  "indépendant développeur web Annecy",
  "prestataire site web Annecy",
  "prestataire digital Annecy",
  "créateur de site Annecy",
  "concepteur site web Annecy",
  "intégrateur web Annecy",
  "site web Annecy",
  "site internet Annecy",
  "création site web Annecy",
  "création site internet Annecy",
  "création de site web sur mesure",
  "création site vitrine Annecy",
  "création site entreprise Annecy",
  "création site pour profession libérale",
  "création site pour indépendant",
  "création site pour association",
  "création site pour collectivité",
  "création site pour franchise",
  "création site pour marque",
  "création site pour lancement produit",
  "site vitrine Annecy",
  "site vitrine professionnel",
  "site vitrine haut de gamme",
  "site vitrine élégant",
  "site vitrine rapide",
  "site one page",
  "site one page Annecy",
  "site une page",
  "landing page Annecy",
  "landing page conversion",
  "page d'atterrissage",
  "squeeze page",
  "page capture leads",
  "refonte site web Annecy",
  "refonte site internet Annecy",
  "refonte totale site",
  "refonte UX",
  "refonte UI",
  "modernisation site ancien",
  "migration site web",
  "migration contenu site",
  "changement de CMS",
  "changement d’hébergement site",
  "maintenance site web",
  "maintenance corrective",
  "maintenance évolutive",
  "TMA site web",
  "hébergement site web",
  "hébergement site France",
  "hébergement Europe RGPD",
  "infogérance site",
  "supervision site web",
  "monitoring uptime",
  "sauvegardes site automatiques",
  "mise à jour sécurité site",
  "correctifs plugin",
  "site sur mesure",
  "site clé en main",
  "site pack",
  "site professionnel",
  "site artisan Annecy",
  "site artisan France",
  "site PME Annecy",
  "site TPE Annecy",
  "site ETI",
  "site restaurant Annecy",
  "site bar Annecy",
  "site café Annecy",
  "site traiteur Annecy",
  "site hotel Annecy",
  "site tourisme Annecy",
  "site événementiel",
  "site festival",
  "site concert",
  "site location saisonnière",
  "site chalet",
  "site gîte",
  "portfolio en ligne",
  "book en ligne",
  "site catalogue Annecy",
  "site catalogue B2B",
  "site institutionnel",
  "site corporate Annecy",
  "site groupe",
  "site filiale marque",
  "site multilingue",
  "site bilingue",
  "site FR EN",
  "hreflang site",
  "internationalisation web",
  "localisation site",
  "traduction contenu site",
  "responsive design",
  "site responsive",
  "mobile first",
  "design adaptatif",
  "breakpoints design",
  "typographie responsive",
  "grille CSS",
  "accessibilité web",
  "RGAA",
  "WCAG AA",
  "contraste accessibilité",
  "navigation clavier",
  "lecteur écran",
  "aria labels",
  "performance web",
  "Core Web Vitals",
  "LCP optimisation",
  "CLS optimisation",
  "INP optimisation",
  "FID optimisation",
  "lazy loading",
  "images optimisées",
  "WebP",
  "AVIF",
  "prefetch",
  "preconnect",
  "cache navigateur",
  "compression Brotli gzip",
  "SEO technique",
  "audit SEO technique",
  "maillage interne",
  "architecture sémantique",
  "silos thématiques",
  "pages piliers SEO",
  "maillage cocoon",
  "balisage sémantique HTML5",
  "balise title optimisée",
  "meta description CTR",
  "balises Hn hiérarchie",
  "schema markup",
  "données structurées JSON-LD",
  "rich results Google",
  "référencement naturel",
  "SEO local",
  "référencement Annecy",
  "visibilité Google Maps",
  "pack local SEO",
  "fiche entreprise locale",
  "Google Business Profile",
  "avis Google entreprise",
  "mots-clés locaux longue traîne",
  "SERPs locales",
  "netlinking",
  "backlinks naturels",
  "backlinks qualitatifs",
  "contenu SEO",
  "rédaction web SEO",
  "tunnel de conversion",
  "CRO optimisation",
  "AB testing landing",
  "copywriting web",
  "microcopy UX",
  "storytelling de marque web",
  "identité digitale",
  "identité visuelle site",
  "image de marque web",
  "charte graphique site internet",
  "brand guidelines web",
  "design UX",
  "design UI",
  "expérience utilisateur",
  "parcours utilisateur",
  "wireframe",
  "maquette site web",
  "prototype interactif",
  "design system",
  "UI kit",
  "direction artistique web",
  "webdesign Annecy",
  "animation web",
  "micro-interactions",
  "graphiste web Annecy",
  "site premium",
  "site haut de gamme",
  "site luxe",
  "site mode",
  "site immobilier agence locale",
  "site promoteur programme neuf landing",
  "site architecte Annecy",
  "portfolio architecte décorateur site",
  "site photographe",
  "site artiste plasticien",
  "site marchand biens conseil financier landing",
  "cabinet conseil site vitrine",
  "site santé informations patients léger CMS",
  "garage artisan BTP artisans site chantier refs",
  "site culture théâtre événements",
  "association billetterie adhésion site",
  "ONG fundraising site",
  "startup MVP site SaaS scaling",
  "marketplace communautaire portail léger notion",
  "extranet client sécurisé",
  "audit site web",
  "audit UX",
  "cahier des charges web",
  "spécifications fonctionnelles site",
  "accompagnement projet Agile web",
  "lancement site production",
  "formation CMS équipe rédactions",
  "support évolutivité site périmètre",
  "SEO-friendly arborescence",
  "breadcrumbs navigation",
  "schema Product ecommerce",
  "FAQ structurée rich snippet",

  "conversion site web",
  "formulaire contact multi-étapes",
  "HubSpot Salesforce intégration contacts",
  "Mailchimp Brevo marketing automation léger",
  "pixels Meta GA4 événements conversion",
  "bandeau cookies CMP conforme",

  "développement web Annecy",
  "développeur web Annecy",
  "intégration web",
  "front-end React Next.js",
  "site headless",
  "JAMstack",
  "SSG ISR Next SEO",
  "API REST intégrations",
  "PWA progression offline-léger",
  "WordPress thème custom",
  "Woocommerce boutique",
  "Shopify développements sections",

  "e-commerce Annecy",
  "boutique en ligne",
  "vente en ligne",
  "Stripe paiement carte",
  "abonnements récurrent léger Stripe",

  "blog entreprise",
  "éditorial web",
  "HowTo markup tutoriel",

  "typographie web",
  "polices web",
  "icônes sur mesure",
  "mockup site présentateur pitch",

  "déploiement Vercel",
  "CDN performance",
  "nom de domaine",
  "email professionnel MX SPF DKIM",

  "Open Graph partages preview",
  "Twitter Card grande image OG 1200x630",

  "plan du site",
  "sitemap",
  "robots crawl",
  "404 personnalisée",
  "301 migration refonte redirections exhaustive",

  "HTTPS HSTS",
  "RGPD site web",
  "mentions légales site",
  "politique confidentialité",
  "hébergement données UE",

  "Annecy",
  "Haute-Savoie",
  "74",
  "Grand Annecy",
  "Rumilly",
  "Aix-les-Bains",
  "La Clusaz",
  "Megève",
  "Chambéry",
  "Albertville",
  "Genève",
  "Suisse romande",
  "Lyon remote mission",
  "Auvergne-Rhône-Alpes",
  "lac d’Annecy",
  "création site Rhône-Alpes",
  "agence web Haute-Savoie",
  "studio UX Annecy",
  "refonte digitale",
  "mission remote France",

  "recrutement site employeurs marque careers",
  "presse médias téléchargements",

  "Lighthouse performance budget",
  "optimisation images next image",
  "third-party audit INP CLS",
  "latin extended français polices",

  "veille concurrent SEO",
  "benchmark UX secteur",
  "FAQ longue traîne locale",

  "Calendly prise RDV site",
  "WhatsApp Business lien mobile",

  "i18n Next routing hreflang prudent",
  "SEO multilingue sans duplicate",

  "Search Console surveillance index",
  "noindex pages peu utiles",

  "accessibilité focus visible RGAA",

  "franchises template site localisations",

  "fabrication industrielle site catalogue technique",
  "site laboratoire R&D présentation offre",
  "site cabinet RH recrutement annonces",
  "site formation continue programmes syllabus",
  "site événements corporate RSVP invitations",
  "site FMCG storytelling produit retail digital",
  "site syndic infos résidents téléchargements",
  "site office tourisme multi-sections agendas",
  "site collectivité infos citoyennes accessibles",
  "site ONG plaidoyer newsletter dons",
  "site club sport planning résultats",
  "cabinet médical téléconsultance infos santé",
  "coach bien-être réservation paiement simple",
  "site wedding planner galeries inspirations",
  "site rénovation habitat avant après",
  "installateur véhicule électrique bornes funnel",
  "marque sport outdoor storytelling produit tech",
  "cosmétiques naturels mentions INCI conformité",
  "wine domain vignoble storytelling dégustation résa",
  "site immobilier SEO annonces enrichies données",
  "site avocats barreau contenus généraux prudence métier",
  "expert-comptable vitrine références sectorielles",
  "guides PDF lead magnet téléchargement formulaire gated",
  "webinaire inscription landing zoom teams",
  "configurateur devis projet questionnaire prix",
  "roadmap backlog priorisation valeur business",
  "atelier personas B2C B2B alignement UX",
  "progressive JPEG formats nextgen légers",
  "service worker léger cache assets statiques",
  "honeypot rate limit spam formulaires",
  "CGV téléchargeables site boutique légal ecommerce",
  "multicanal UTM disciplined planning campagnes",
  "heatmap hotjar ux parcours clients",
  "sessions replay consentement utilisateur prudent",
  "arborescence profonde équilibrée crawl depth",
  "pagination numérotée long tail commerce SEO",
  "pillar cluster evergreen maillage contextualisé",
  "sites multi-magasins pages locales géo",
  "facettes navigation duplication canonical prudent",
  "portail membres téléchargements sécurisé",
  "staging preview QA client avant mise prod",
  "design tokens WCAG contrastes accessibles politiques marque",
  "illustrations SVG Lottie légers marketing loops",
  "page équipe bios photos cohérentes tonalité studio",
  "page méthode process transparent livrables jalons",

  "intégration Airtable Notion backends légers gestion données",
  "zapier make automatisations marketing ops répétitives",

  "metadata OpenGraph dynamiques routes App Router",

  "schema BreadcrumbList données enrichies SERP",

  "contenu ISR programmé publication timezone Europe Paris",

  "landing Google Ads Quality Score alignment copy",

  "landing Meta Ads créatives variantes AB tests rapides",

  "données structurées Organization marque",
  "veille mises à jour dépendances npm sécurité",
];